language: cpp

env:
        - ENABLE_INTERNAL_METEODISTR=ON
        - ENABLE_INTERNAL_METEODISTR=OFF
        - TEST_NAME=Bro
        - TEST_NAME=Calabria
        - TEST_NAME=no_reflection
        - TEST_NAME=small-example-onlyEnergy
        - TEST_NAME=ColdelaPorte
        - TEST_NAME=small-example-channel
        - TEST_NAME=CostantMeteo
        - TEST_NAME=small-example-channel
        - TEST_NAME=small-example
        - TEST_NAME=PSQL_test
        - TEST_NAME=panola
        - TEST_NAME=example
        - TEST_NAME=prealpiC
        - TEST_NAME=Jungfraujoch
        - TEST_NAME=bonn_2
        - TEST_NAME=Mazia
        - TEST_NAME=Borden05m_nopit_001

#installing the dependencies: proj and meteoio libraries
install:
        #install required boost libraries
        - sudo apt-get install libboost-all-dev
        - sudo apt-get install doxygen

        #it's supposed to be run in a environment with the access to apt-get (following travis guide)
        - sudo apt-get install libproj-dev
        #in case it is needed you can install a specific version of the library
        #- apt-get install libproj-dev=version

        #meteio install
        - wget https://models.slf.ch/p/meteoio/downloads/get/MeteoIO-2.5.1-src.tar.gz
        - tar xvf MeteoIO-2.5.1-src.tar.gz meteoio
        - cd meteoio/
        #add dependency for proj4 in cmake for meteoio
        - cmake -DPROJ4:BOOL=ON .
        - cmake -LAH
        - make && sudo make install
        - cd ..

        #install nosetests dependency
        - sudo apt-get install python-pandas
        - sudo apt-get install python-nose

#actually build the geotop program
script:
        #build geotop with meteoio disabled
        - cmake -DENABLE_INTERNAL_METEODISTR:BOOL=$ENABLE_INTERNAL_METEODISTR .
        - make
        #make tests with this environment
        - ctest -R $TEST_NAME  .
        #- ctest -R Bro .
        #- cat Testing/Temporary/LastTest.log
        #- cd tests/1D
        #- nosetests -v test_runner.py

#choosing the compiler
compiler:
        - g++
