language: cpp

env:
        - ENABLE_INTERNAL_METEODISTR=ON
        - ENABLE_INTERNAL_METEODISTR=OFF

#installing the dependencies: proj and meteoio libraries
install:
        #install required boost libraries
        - sudo apt-get install libboost-all-dev
        - sudo apt-get install doxygen

        #it's supposed to be run in a environment with the access to apt-get (following travis guide)
        - sudo apt-get install libproj-dev
        #in case it is needed you can install a specific version of the library
        #- apt-get install libproj-dev=version

        #meteio install
        - wget https://models.slf.ch/p/meteoio/downloads/get/MeteoIO-2.5.1-src.tar.gz
        - tar xvf MeteoIO-2.5.1-src.tar.gz meteoio
        - cd meteoio/
        #add dependency for proj4 in cmake for meteoio
        - cmake -DPROJ4:BOOL=ON .
        - cmake -LAH
        - make && sudo make install
        - cd ..

        #install nosetests dependency
        - sudo apt-get install python-pandas
        - sudo apt-get install python-nose

#actually build the geotop program
script:
        #build geotop with meteoio disabled
        - cmake -DENABLE_INTERNAL_METEODISTR:BOOL=$ENABLE_INTERNAL_METEODISTR .
        - make -Wno-unused-parameter
        #make tests with this environment
        - if [ "$ENABLE_INTERNAL_METEODISTR" = "OFF" ]; then ctest -j17 -E "bonn_1|bonn_2|CostantMeteo" .; else ctest -j17 .; fi
        #- ctest -E "bonn_1|bonn_2|CostantMeteo" .
        #- ctest -R Bro .
        #- cat Testing/Temporary/LastTest.log
        #- cd tests/1D
        #- nosetests -v test_runner.py

#choosing the compiler
compiler:
        - g++
