sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - meson
      - numdiff
      - ninja-build


script:
  - meson build
  - cd build
  - ninja
  - meson test --suite geotop:unit_tests

