sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - numdiff
      - ninja-build

python:
  - "3.6"

before_install:
  - git clone https://github.com/mesonbuild/meson.git _meson
  - export PATH="$PWD/_meson:$PATH"

script:
  - meson.py build
  - cd build
  - ninja
  - meson.py test --suite geotop:unit_tests

